site_name: 'City Data Model - Part 1: Foundation level concepts'
site_description: This ontology forms the basis of ISO/IEC 5087-1, which specifies
  the foundational level concepts for cities.
repo_url: https://github.com/ISO-TC204/ontology-cdm-p1-v1
nav:
- Home: index.md
- Activity Pattern:
  - Activity Pattern Overview: classes/activity.md
  - Classes:
    - Activity: classes/Activity.md
    - Activity Status: classes/ActivityStatus.md
    - Activity Thing: classes/ActivityThing.md
    - Conjunctive State: classes/ConjunctiveState.md
    - Disjunctive State: classes/DisjunctiveState.md
    - Manifestation State: classes/ManifestationState.md
    - Non Terminal State: classes/NonTerminalState.md
    - State: classes/State.md
    - State Status: classes/StateStatus.md
    - Terminal State: classes/TerminalState.md
  - Properties:
    - achievedAt: properties/achievedAt.md
    - ActivityObjectProperty: properties/ActivityObjectProperty.md
    - beginOf: properties/beginOf.md
    - causedByActivity: properties/causedByActivity.md
    - causesState: properties/causesState.md
    - conjunctiveAchievedAt: properties/conjunctiveAchievedAt.md
    - disjunctiveAchievedAt: properties/disjunctiveAchievedAt.md
    - effectOf: properties/effectOf.md
    - enabledByState: properties/enabledByState.md
    - enablesActivity: properties/enablesActivity.md
    - endOf: properties/endOf.md
    - hasDecomp: properties/hasDecomp.md
    - hasEffect: properties/hasEffect.md
    - hasPrecondition: properties/hasPrecondition.md
    - hasStatus: properties/hasStatus.md
    - hasSubactivity: properties/hasSubactivity.md
    - hasSubstate: properties/hasSubstate.md
    - occursAfter: properties/occursAfter.md
    - occursAt: properties/occursAt.md
    - occursBefore: properties/occursBefore.md
    - occursDirectlyAfter: properties/occursDirectlyAfter.md
    - occursDirectlyBefore: properties/occursDirectlyBefore.md
    - preconditionOf: properties/preconditionOf.md
    - satisfiedBy: properties/satisfiedBy.md
    - scheduledFor: properties/scheduledFor.md
    - terminalAchievedAt: properties/terminalAchievedAt.md
- Agent Pattern:
  - Agent Pattern Overview: classes/agent.md
  - Classes:
    - Agent: classes/Agent.md
    - Agent Thing: classes/AgentThing.md
  - Properties:
    - AgentObjectProperty: properties/AgentObjectProperty.md
    - performedBy: properties/performedBy.md
    - performs: properties/performs.md
- Agreement Pattern:
  - Agreement Pattern Overview: classes/agreement.md
  - Classes:
    - Agent: classes/Agent.md
    - Agreement: classes/Agreement.md
    - Agreement Thing: classes/AgreementThing.md
    - Atomic Agreement: classes/AtomicAgreement.md
    - Complex Agreement: classes/ComplexAgreement.md
    - Conjunctive Agreement: classes/ConjunctiveAgreement.md
    - Disjunctive Agreement: classes/DisjunctiveAgreement.md
  - Properties:
    - agentInvolvedIn: properties/agentInvolvedIn.md
    - AgreementObjectProperty: properties/AgreementObjectProperty.md
    - commitsToActivity: properties/commitsToActivity.md
    - establishedOn: properties/establishedOn.md
    - hasClaim: properties/hasClaim.md
    - hasDuty: properties/hasDuty.md
    - hasNoClaim: properties/hasNoClaim.md
    - hasPrivilege: properties/hasPrivilege.md
    - hasSubAgreement: properties/hasSubAgreement.md
    - involvesAgent: properties/involvesAgent.md
    - validFor: properties/validFor.md
    - validIn: properties/validIn.md
- Change Pattern:
  - Change Pattern Overview: classes/ChangePattern.md
  - Classes:
    - Change Thing: classes/ChangeThing.md
    - First Manifestation: classes/FirstManifestation.md
    - Manifestation: classes/Manifestation.md
  - Properties:
    - ChangeObjectProperty: properties/ChangeObjectProperty.md
    - existsAt: properties/existsAt.md
    - hasFirstManifestation: properties/hasFirstManifestation.md
    - hasLatestManifestation: properties/hasLatestManifestation.md
    - hasManifestation: properties/hasManifestation.md
    - hasNextManifestation: properties/hasNextManifestation.md
    - hasPreviousManifestation: properties/hasPreviousManifestation.md
    - precedesManifestation: properties/precedesManifestation.md
- City Units Pattern:
  - City Units Pattern Overview: classes/city-units.md
  - Classes:
    - Acceleration: classes/Acceleration.md
    - Acceleration Unit: classes/AccelerationUnit.md
    - Amount Of Money: classes/AmountOfMoney.md
    - Area: classes/Area.md
    - Area Unit: classes/AreaUnit.md
    - Capacity: classes/Capacity.md
    - Capacity Size: classes/CapacitySize.md
    - Cardinality Measure: classes/CardinalityMeasure.md
    - Cardinality Unit Per Time: classes/CardinalityUnitPerTime.md
    - City Units Thing: classes/CityUnitsThing.md
    - Duration: classes/Duration.md
    - Geo_position_unit: classes/Geo_Position_unit.md
    - Length: classes/Length.md
    - Length Unit: classes/LengthUnit.md
    - Mass: classes/Mass.md
    - Mass Unit: classes/MassUnit.md
    - Monetary Value: classes/MonetaryValue.md
    - Ratio: classes/Ratio.md
    - Speed: classes/Speed.md
    - Speed Unit: classes/SpeedUnit.md
    - Time Unit: classes/TimeUnit.md
    - Value Of Money: classes/ValueOfMoney.md
    - Volume: classes/Volume.md
    - Volume Unit: classes/VolumeUnit.md
  - Properties:
    - CityUnitObjectProperty: properties/CityUnitObjectProperty.md
    - CityUnitsDataProperty: properties/CityUnitsDataProperty.md
    - hasRelativeYear: properties/hasRelativeYear.md
- Core Pattern:
  - Core Pattern Overview: classes/Core.md
  - Classes:
    - Cdm Thing: classes/CdmThing.md
    - Foundational Cdm Thing: classes/FoundationalCdmThing.md
  - Properties:
    - CdmDataProperty: properties/CdmDataProperty.md
    - CdmObjectProperty: properties/CdmObjectProperty.md
    - FoundationalCdmDataProperty: properties/FoundationalCdmDataProperty.md
    - FoundationalCdmObjectProperty: properties/FoundationalCdmObjectProperty.md
- Generic Properties Pattern:
  - Generic Properties Pattern Overview: classes/generic-properties.md
  - Properties:
    - GeneralDataProperty: properties/GeneralDataProperty.md
    - hasDescription: properties/hasDescription.md
    - hasIdentifier: properties/hasIdentifier.md
    - hasName: properties/hasName.md
- Mereology Pattern:
  - Mereology Pattern Overview: classes/mereology.md
  - Properties:
    - aggregateOf: properties/aggregateOf.md
    - aggregateOver: properties/aggregateOver.md
    - aggregationOf: properties/aggregationOf.md
    - componentOf: properties/componentOf.md
    - hasComponent: properties/hasComponent.md
    - hasProperPart: properties/hasProperPart.md
    - immediateComponentOf: properties/immediateComponentOf.md
    - MereologyObjectProperty: properties/MereologyObjectProperty.md
    - partOf: properties/partOf.md
    - properPartOf: properties/properPartOf.md
- Organization Structure Pattern:
  - Organization Structure Pattern Overview: classes/organization-structure.md
  - Classes:
    - Organization: classes/Organization.md
    - Organization Thing: classes/OrganizationThing.md
- Recurring Event Pattern:
  - Recurring Event Pattern Overview: classes/recurring-event.md
  - Classes:
    - Daily Recurring Event: classes/DailyRecurringEvent.md
    - Exception Day: classes/ExceptionDay.md
    - Monthly Recurring Event: classes/MonthlyRecurringEvent.md
    - Recurring Event: classes/RecurringEvent.md
    - Recurring Event Thing: classes/RecurringEventThing.md
    - Weekly Recurring Event: classes/WeeklyRecurringEvent.md
    - Yearly Recurring Event: classes/YearlyRecurringEvent.md
  - Properties:
    - beginsRecurringState: properties/beginsRecurringState.md
    - beginsRecurringTime: properties/beginsRecurringTime.md
    - endDayOfWeek: properties/endDayOfWeek.md
    - endMonth: properties/endMonth.md
    - endsRecurringState: properties/endsRecurringState.md
    - endsRecurringTime: properties/endsRecurringTime.md
    - endTime: properties/endTime.md
    - hasDayOfWeek: properties/hasDayOfWeek.md
    - hasMonth: properties/hasMonth.md
    - hasOccurrence: properties/hasOccurrence.md
    - hasSubRecurringEvent: properties/hasSubRecurringEvent.md
    - onDateTimeDescription: properties/onDateTimeDescription.md
    - RecurringEventDataProperty: properties/RecurringEventDataProperty.md
    - RecurringEventObjectProperty: properties/RecurringEventObjectProperty.md
    - recursAddition: properties/recursAddition.md
    - recursExcept: properties/recursExcept.md
    - startTime: properties/startTime.md
- Resource Pattern:
  - Resource Pattern Overview: classes/resource.md
  - Classes:
    - Consume State: classes/ConsumeState.md
    - Divisible Resource: classes/DivisibleResource.md
    - Non Divisible Resource: classes/NonDivisibleResource.md
    - Planned Allocation: classes/PlannedAllocation.md
    - Produce State: classes/ProduceState.md
    - Release State: classes/ReleaseState.md
    - Resource: classes/Resource.md
    - Resource Thing: classes/ResourceThing.md
    - Terminal Resource State: classes/TerminalResourceState.md
    - Use State: classes/UseState.md
  - Properties:
    - capacityInUse: properties/capacityInUse.md
    - consumedBy: properties/consumedBy.md
    - forResource: properties/forResource.md
    - forState: properties/forState.md
    - hasAllocation: properties/hasAllocation.md
    - hasAsset: properties/hasAsset.md
    - hasAvailableCapacity: properties/hasAvailableCapacity.md
    - hasCapacity: properties/hasCapacity.md
    - hasOwner: properties/hasOwner.md
    - hasQuantity: properties/hasQuantity.md
    - hasResource: properties/hasResource.md
    - ownedBy: properties/ownedBy.md
    - participatesIn: properties/participatesIn.md
    - ResourceObjectProperty: properties/ResourceObjectProperty.md
    - resourceOf: properties/resourceOf.md
    - usedBy: properties/usedBy.md
- Spatial Loc Pattern:
  - Spatial Loc Pattern Overview: classes/spatial-loc.md
  - Classes:
    - Location: classes/Location.md
    - Spatial Loc Thing: classes/SpatialLocThing.md
  - Properties:
    - associatedLocation: properties/associatedLocation.md
    - hasLocation: properties/hasLocation.md
    - hasSerialization: properties/hasSerialization.md
    - LocationDataProperty: properties/LocationDataProperty.md
    - LocationObjectProperty: properties/LocationObjectProperty.md
    - nonTangentialProperPart: properties/nonTangentialProperPart.md
    - tangentialProperPart: properties/tangentialProperPart.md
site_url: https://isotc204.org/ontology-cdm-p1-v1
copyright: <p xmlns:cc="http://creativecommons.org/ns#" xmlns:dct="http://purl.org/dc/terms/">
  <a href="https://creativecommons.org/licenses/by/4.0/?ref=chooser-v1" target="_blank"
  rel="license noopener noreferrer" style="display:inline-block;">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;"
  src="https://mirrors.creativecommons.org/presskit/icons/cc.svg?ref=chooser-v1" alt=""><img
  style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg?ref=chooser-v1"
  alt=""></a></p>
theme:
  name: material
  features:
  - content.code.copy
  - content.status
  - content.tooltips
  - icons
  - navigation.path
  - navigation.top
  icon:
    repo: fontawesome/brands/github
    admonition:
      question: fontawesome/solid/comments
  palette:
  - scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
extra_css:
- stylesheets/extra.css
extra_javascript:
- https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
- javascripts/tablesort.js
plugins:
- search
- git-revision-date-localized:
    type: date
markdown_extensions:
- abbr
- admonition
- attr_list
- def_list
- md_in_html
- meta
- footnotes
- pymdownx.blocks.caption
- pymdownx.details
- pymdownx.highlight:
    anchor_linenums: true
    line_spans: __span
    pygments_lang_class: true
    use_pygments: true
- pymdownx.inlinehilite
- pymdownx.snippets:
    base_path: docs
    check_paths: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: ''
- pymdownx.tabbed:
    alternate_style: true
- toc:
    permalink: true
extra:
  search:
    highlight: true
  hide:
  - title
  version:
    provider: mike
    alias: true
    default: latest
